# Generated by Django 4.1.1 on 2023-07-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='f_fabricacion',
        ),
    ]
