# Generated by Django 4.1.1 on 2023-07-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_remove_producto_f_fabricacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='f_fabricacion',
            field=models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=1, verbose_name='Fecha de Fabricacion'),
            preserve_default=False,
        ),
    ]
