# Generated by Django 4.1.1 on 2023-07-24 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_producto_f_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorgeneral',
            name='laboratorio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorio', verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorio', verbose_name='Laboratorio'),
        ),
    ]
