# Generated by Django 4.1.1 on 2023-07-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_actualizado_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='num_visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
